apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-api
  template:
    metadata:
      labels:
        app: ocr-api
    spec:
      containers:
      - name: ocr-api
        image: jp.icr.io/mile-iisc/ocr-api:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-api
  labels:
    app: ocr-api
spec:
  type: LoadBalancer
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: ocr-api